/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dpiqb;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        new TicTacToe().buildGame().start();
    }
}
